name: WarpsCreator
main: me.demonis.warpscreator.Main
author: Demonis
version: 1.0
description: Plugin to create warps.
commands:
  warp:
    description: Main command for WarpsCreator.
    permission: warpscreator.use
    aliases: [warps]